---
name: Pre-Commit CI Check
on:
    push:
        branches: [main, master]
        paths:
            - '**.h'
            - '**.hh'
            - '**.hxx'
            - '**.hpp'
            - '**.c'
            - '**.cc'
            - '**.cpp'
            - '**.cxx'
            - CMakeLists.txt
            - '**.cmake'
            - '**.yml'
            - '**.yaml'
            - .pre-commit-config.yaml
    pull_request:
        branches: [main, master]
        paths:
            - '**.h'
            - '**.hh'
            - '**.hxx'
            - '**.hpp'
            - '**.c'
            - '**.cc'
            - '**.cpp'
            - '**.cxx'
            - CMakeLists.txt
            - '**.cmake'
            - '**.yml'
            - '**.yaml'
            - .pre-commit-config.yaml

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    pre-commit-check:
        name: Run Pre-Commit Hooks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Install and verify cppcheck
              run: |
                  sudo apt update -y
                  sudo apt install -y cppcheck
                  which cppcheck
                  cppcheck --version

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
                  cache: ''

            - name: Install dependencies and configure PATH
              run: |
                  python -m pip install --upgrade pip
                  pip install pre-commit cpplint

                  echo "$HOME/.local/bin" >> $GITHUB_PATH

                  which pre-commit
                  which cpplint
                  cpplint --version

            - name: Cache pre-commit dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
                  restore-keys: pre-commit-

            - name: Run pre-commit hooks
              run: pre-commit run --all-files
              env:
                  TERM: xterm-256color
